export const constants = {
  links: {
    github: "https://git.new/prexo",
    discord: "https://l.devwtf.in/plura-dc",
    x: "https://l.devwtf.in/plura-x",
  },
};

export const pricingCardConfig = [
  {
    name: "Basic",
    isFeatured: false,
    isFree: true,
    currency: "$",
    btn: "Get Prexo Basic",
    priceMonthly: 0,
    priceYearly: 0,
    beforePriceMonthly: 19,
    beforePriceYearly: 19,
    discountYearly: 100,
    discountMonthly: 100,
    benifits: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
  },

  {
    name: "Pro",
    isFeatured: true,
    isFree: false,
    currency: "$",
    btn: "Get Prexo Pro",
    priceMonthly: 15,
    priceYearly: 679,
    beforePriceMonthly: 30,
    beforePriceYearly: 659,
    discountYearly: 334.03,
    discountMonthly: 50,
    benifits: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
  },
];
